### ISSUE TITLE
panic: close of closed channel due to multiple `JobRunningResolution` message

### ISSUE THREAD

**Issue by lokielse** [signalfx/signalfx-go#205]
```
JobStartControlMessage
MetadataMessage
MetadataMessage
MetadataMessage
MetadataMessage
MetadataMessage
MetadataMessage
MetadataMessage
MetadataMessage
DataMessage
InfoMessage.JobRunningResolution
InfoMessage.JobInitialMaxDelay
DataMessage
DataMessage
DataMessage
DataMessage
DataMessage
DataMessage
DataMessage
DataMessage
DataMessage
DataMessage
DataMessage
InfoMessage.JobRunningResolution
panic: close of closed channel

goroutine 103 [running]:
github.com/signalfx/signalfx-go/signalflow/v2.(*asyncMetadata[...]).Set(0xc00311fd70, 0xea60?)
	my-project/vendor/github.com/signalfx/signalfx-go/signalflow/v2/computation.go:365 +0x5c
github.com/signalfx/signalfx-go/signalflow/v2.(*Computation).processMessage(0xc000168000, {0x1ed7f18?, 0xc000e0c630?})
	my-project/vendor/github.com/signalfx/signalfx-go/signalflow/v2/computation.go:202 +0x6a6
github.com/signalfx/signalfx-go/signalflow/v2.(*Computation).watchMessages(0xc000168000)
	my-project/vendor/github.com/signalfx/signalfx-go/signalflow/v2/computation.go:173 +0x49
github.com/signalfx/signalfx-go/signalflow/v2.newComputation.func1()
	my-project/vendor/github.com/signalfx/signalfx-go/signalflow/v2/computation.go:81 +0x25
created by github.com/signalfx/signalfx-go/signalflow/v2.newComputation in goroutine 29
	my-project/vendor/github.com/signalfx/signalfx-go/signalflow/v2/computation.go:80 +0x356

```

**Comment by benkeith-splunk** [comment]
This should have been fixed by #206
